### ISSUE TITLE
Error of translation

### ISSUE THREAD

**Issue by ghost** [InternalError503/restart-my-chrome#1]
Hello, in option we can rule the time we want to erase, "the last hour", "the last week", "the last day" for each it has a good translation in french but for "the beginning of time", it's an error. The good tranlation of "the beginning of time" is "le début des temps" and that's "le début de l'heure", in english "the beginning of the hour" so it's confused and not at all "the beginning of time"  want to mean in english. Sorry for my bad english I'm french.

**Comment by InternalError503** [comment]
Hi alain1965

Thank you for reporting it, I have passed your correction over and it will appear in the next update.

Thank you very much for your help.
